### ISSUE TITLE
IMDB & RT rating to summary no longer works

### ISSUE THREAD

**Issue by Fyx0z** [haeY/OpenMovieDatabase.bundle#10]
The "Add IMDB & Rotten Tomatoes rating to summary" no longer works for me after upgrading to 0.9.17.2. How can I fix this? Thanks!

**Comment by yoasif** [comment]
Also seeing this issue on Version 0.9.16.6 on Linux.

**Comment by sander1** [comment]
Do you have the agent set as primary agent for the movie section, or as first agent in the list if used as a secondary agent?
This agent cannot change summaries provided by other agents.

**Comment by razorloves** [comment]
Working fine for me on version 0.9.16.6 windows 10.
I have my movie library set to use "The Movie Database" agent.
And i have this plugin set as the first agent in the list.

**Comment by Fyx0z** [comment]
My movie library is set to "Freebase" and I use it as a secondary agent, see screenshot:
[http://www.imagebam.com/image/b058d5490977430](url)

This setup has worked for me for over a year, and it suddenly stopped working about a week or so ago.

**Comment by yoasif** [comment]
This is how I have it set up:

http://imgur.com/a/6OxzO

I'm getting descriptions, but not the added IMDB and RT scores.

**Comment by haeY** [comment]
Latest commit (https://github.com/haeY/OpenMovieDatabase.bundle/commit/de96046df8618f169eea337afd91798449ee1d6d) should fix the issues.

**Comment by yoasif** [comment]
Happy to report that the new build with version 0.9.16.6 on Linux works great. Thanks for the quick fix!

**Comment by Fyx0z** [comment]
Awesome! Working for me as well!
