### ISSUE TITLE
No longer works with Freebase shut down?

### ISSUE THREAD

**Issue by austinarchibald** [haeY/OpenMovieDatabase.bundle#7]
Freebase is shut down, and since moving to the Movie Database agent, Plex no longer pulls in metadata from OMDB even though I have it listed first in priority. Any ideas?

Update: Freebase is working for some reason today. No idea why or when it'll be shut down again, but still need to figure out how to get this to work with the Movie Database Agent.

**Comment by haeY** [comment]
Fixed for The Movie Database agent with https://github.com/haeY/OpenMovieDatabase.bundle/commit/f2e6c335a283d9095a4d101b5ff09738b1a9bd55
